//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebdriverFramework.VK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebdriverFramework.VK.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wall.createComment.
        /// </summary>
        internal static string CreateComment {
            get {
                return ResourceManager.GetString("CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wall.post.
        /// </summary>
        internal static string CreatePost {
            get {
                return ResourceManager.GetString("CreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wall.delete.
        /// </summary>
        internal static string DeletePost {
            get {
                return ResourceManager.GetString("DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wall.edit.
        /// </summary>
        internal static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;extendeed=true.
        /// </summary>
        internal static string Extended {
            get {
                return ResourceManager.GetString("Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d+.
        /// </summary>
        internal static string GetNumberRegex {
            get {
                return ResourceManager.GetString("GetNumberRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://images2.alphacoders.com/591/59190.jpg.
        /// </summary>
        internal static string ImageSourse {
            get {
                return ResourceManager.GetString("ImageSourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;item_id=.
        /// </summary>
        internal static string LikedObject {
            get {
                return ResourceManager.GetString("LikedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;type=post.
        /// </summary>
        internal static string LikeType {
            get {
                return ResourceManager.GetString("LikeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoperftester@gmail.com.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PuV6j_.2&amp;$m9h?UY.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;attachment=photo381108928,C:\Users\IEUser\Downloads\vader.png.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;post_id=.
        /// </summary>
        internal static string PostId {
            get {
                return ResourceManager.GetString("PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likes.isLiked.
        /// </summary>
        internal static string PostIsLiked {
            get {
                return ResourceManager.GetString("PostIsLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message=.
        /// </summary>
        internal static string PostMessage {
            get {
                return ResourceManager.GetString("PostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000.
        /// </summary>
        internal static string POSTTimeOut {
            get {
                return ResourceManager.GetString("POSTTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 904da13c62ef685c2d17cdd3f3fb8430dcb1e6f23311809ba5b79e18fa4e97334dc30da82610f31b575ba.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owner_id=381108928.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.getWallUploadServer.
        /// </summary>
        internal static string WallUploadServer {
            get {
                return ResourceManager.GetString("WallUploadServer", resourceCulture);
            }
        }
    }
}
